services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"

  simulator:
    build:
      context: ./simulator
    container_name: ekf-simulator
    depends_on:
      - mqtt

  ekf:
    build:
      context: ./ekf_filter
    container_name: ekf-filter
    depends_on:
      - mqtt
  
  visualizer:
    build:
      context: ./visualizer_ui
    container_name: ekf-visualizer
    depends_on:
      - mqtt
    environment:
      DISPLAY: ":0"
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    user: "0:0"
 